pipeline {
    agent any

    tools {
        maven 'maven3'
    }

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
        IMAGE_TAG = "v${BUILD_NUMBER}"
        IMAGE_NAME = "deepakgholave11/bankapp"
    }

    stages {

        stage('Git Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-deepak',
                    url: 'https://github.com/deepakgholave11/Ultimate-Mega-Project.git'
            }
        }

        stage('Build from CI Directory') {
            steps {
                dir('bankapp-ci') {

                    stage('Compile') {
                        sh "mvn compile"
                    }

                    stage('Testing') {
                        sh "mvn test"
                    }

                    stage('Trivy FS Scan') {
                        sh "trivy fs --format table -o fs-report.html ."
                    }

                    stage('Sonar Analysis') {
                        withSonarQubeEnv('sonar') {
                            sh """
                            ${SCANNER_HOME}/bin/sonar-scanner \
                            -Dsonar.projectKey=bankapp-ci \
                            -Dsonar.projectName=BankApp-CI \
                            -Dsonar.java.binaries=target
                            """
                        }
                    }

                    stage('Quality Gates') {
                        timeout(time: 1, unit: 'HOURS') {
                            waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token'
                        }
                    }

                    stage('Build Package') {
                        sh "mvn package"
                    }

                    stage('Publish to Nexus') {
                        withMaven(globalMavenSettingsConfig: 'devopsshack', maven: 'maven3') {
                            sh "mvn deploy"
                        }
                    }

                    stage('Docker Build') {
                        sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                    }

                    stage('Image Scan') {
                        sh "trivy image ${IMAGE_NAME}:${IMAGE_TAG}"
                    }

                    stage('Docker Push') {
                        withDockerRegistry(credentialsId: 'docker-cred') {
                            sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
                        }
                    }
                }
            }
        }

        stage('Update CD Manifest') {
            steps {
                cleanWs()

                withCredentials([usernamePassword(
                    credentialsId: 'github-deepak',
                    usernameVariable: 'GIT_USERNAME',
                    passwordVariable: 'GIT_PASSWORD'
                )]) {
                    sh '''
                    git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/deepakgholave11/Ultimate-Mega-Project.git
                    cd Ultimate-Mega-Project/bankapp-cd
                    sed -i "s|deepakgholave11/bankapp:.*|deepakgholave11/bankapp:${IMAGE_TAG}|" manifest.yaml
                    git config user.name "Jenkins"
                    git config user.email "deepakgholave11@gmail.com"
                    git add manifest.yaml
                    git commit -m "Update image to ${IMAGE_TAG}"
                    git push origin main
                    '''
                }
            }
        }
    }

    post {
        always {
            emailext(
                subject: "BankApp CI Pipeline - Build ${BUILD_NUMBER}",
                body: "Pipeline Status: ${currentBuild.currentResult}",
                to: 'deepakgholave11@gmail.com',
                from: 'jenkins@bankapp.com'
            )
        }
    }
}
